package com.dam.salesianostriana.calccalorias.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RUTA".
*/
public class RutaDao extends AbstractDao<Ruta, Long> {

    public static final String TABLENAME = "RUTA";

    /**
     * Properties of entity Ruta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Distancia = new Property(1, Double.class, "distancia", false, "DISTANCIA");
        public final static Property Calorias = new Property(2, Double.class, "calorias", false, "CALORIAS");
        public final static Property Fecha = new Property(3, java.util.Date.class, "fecha", false, "FECHA");
        public final static Property Duracion = new Property(4, String.class, "duracion", false, "DURACION");
        public final static Property Id_usuario = new Property(5, Long.class, "id_usuario", false, "ID_USUARIO");
    };

    private DaoSession daoSession;

    private Query<Ruta> usuario_Ruta_usuarioQuery;

    public RutaDao(DaoConfig config) {
        super(config);
    }
    
    public RutaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RUTA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DISTANCIA\" REAL," + // 1: distancia
                "\"CALORIAS\" REAL," + // 2: calorias
                "\"FECHA\" INTEGER," + // 3: fecha
                "\"DURACION\" TEXT," + // 4: duracion
                "\"ID_USUARIO\" INTEGER);"); // 5: id_usuario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RUTA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ruta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double distancia = entity.getDistancia();
        if (distancia != null) {
            stmt.bindDouble(2, distancia);
        }
 
        Double calorias = entity.getCalorias();
        if (calorias != null) {
            stmt.bindDouble(3, calorias);
        }
 
        java.util.Date fecha = entity.getFecha();
        if (fecha != null) {
            stmt.bindLong(4, fecha.getTime());
        }
 
        String duracion = entity.getDuracion();
        if (duracion != null) {
            stmt.bindString(5, duracion);
        }
 
        Long id_usuario = entity.getId_usuario();
        if (id_usuario != null) {
            stmt.bindLong(6, id_usuario);
        }
    }

    @Override
    protected void attachEntity(Ruta entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ruta readEntity(Cursor cursor, int offset) {
        Ruta entity = new Ruta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // distancia
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // calorias
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // fecha
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // duracion
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // id_usuario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ruta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDistancia(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setCalorias(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setFecha(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setDuracion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setId_usuario(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ruta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ruta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Ruta_usuario" to-many relationship of Usuario. */
    public List<Ruta> _queryUsuario_Ruta_usuario(Long id_usuario) {
        synchronized (this) {
            if (usuario_Ruta_usuarioQuery == null) {
                QueryBuilder<Ruta> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id_usuario.eq(null));
                usuario_Ruta_usuarioQuery = queryBuilder.build();
            }
        }
        Query<Ruta> query = usuario_Ruta_usuarioQuery.forCurrentThread();
        query.setParameter(0, id_usuario);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuarioDao().getAllColumns());
            builder.append(" FROM RUTA T");
            builder.append(" LEFT JOIN USUARIO T0 ON T.\"ID_USUARIO\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Ruta loadCurrentDeep(Cursor cursor, boolean lock) {
        Ruta entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuario usuario = loadCurrentOther(daoSession.getUsuarioDao(), cursor, offset);
        entity.setUsuario(usuario);

        return entity;    
    }

    public Ruta loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Ruta> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Ruta> list = new ArrayList<Ruta>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Ruta> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Ruta> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
